USE [master]
GO

/****** Object:  Database [turismo]    Script Date: 21/11/2021 22:20:05 ******/
CREATE DATABASE [turismo]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'turismo', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\turismo.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'turismo_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\turismo_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [turismo].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [turismo] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [turismo] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [turismo] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [turismo] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [turismo] SET ARITHABORT OFF 
GO

ALTER DATABASE [turismo] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [turismo] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [turismo] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [turismo] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [turismo] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [turismo] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [turismo] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [turismo] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [turismo] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [turismo] SET  ENABLE_BROKER 
GO

ALTER DATABASE [turismo] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [turismo] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [turismo] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [turismo] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [turismo] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [turismo] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [turismo] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [turismo] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [turismo] SET  MULTI_USER 
GO

ALTER DATABASE [turismo] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [turismo] SET DB_CHAINING OFF 
GO

ALTER DATABASE [turismo] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [turismo] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [turismo] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [turismo] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [turismo] SET QUERY_STORE = OFF
GO

ALTER DATABASE [turismo] SET  READ_WRITE 
GO

